<a href="https://colab.research.google.com/github/ccastaneda-boot/datawarehouse-seguros/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/ccastaneda-boot/datawarehouse-seguros.git

https://raw.githubusercontent.com/ccastaneda-boot/datawarehouse-seguros/refs/heads/main/data/clientes.csv

In [23]:
url="https://raw.githubusercontent.com/ccastaneda-boot/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

In [25]:
#Lectura del archivo
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [29]:
display(df.head(2))

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN

BLOQUE 2: Exploracion del DATASET (Calidad del dato)

In [28]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [30]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(3030, 7)

In [31]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [32]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [34]:
print("Valores nulos")
print(df.isnull().sum())

Valores nulos
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [36]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3: LIMPIEZA DE DATOS

In [38]:
#Elimina espacios al inicio y al final en columnas de texto
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [39]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [40]:
#Normalizar el email
df['email']=df['email'].str.lower()

In [41]:
#Normalizar genero
df['genero']=df['genero'].str.upper()

In [42]:
#Convertir fecha de nacimiento en formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [48]:
#Normalizar Ciudad
df['ciudad'] = df['ciudad'].str.title()
df['ciudad']= df['ciudad'].astype(str)
df['ciudad']= df['ciudad'].str.strip()
df['ciudad']= df['ciudad'].str.upper()

In [46]:
#Limpieza de segmento
df['segmento']= df['segmento'].astype(str)
df['segmento']= df['segmento'].str.strip()
df['segmento']= df['segmento'].str.upper()

In [47]:
for col in df.columns: print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

BLOQUE 4: VALIDACION DE DATOS

In [49]:
#Crear columna para registrar errores
df['motivo_rechazo']=""

#Validar id_cliente
df.loc[df['id_cliente'].isnull(), "motivo_rechazo"] += "id_clinete nulo; "